### ISSUE TITLE
Modal cuts off at bottom on super wider screen

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/lake-gallery#12]
Intro modal seems to cut off on a super wide screen (it is fine on smaller ones).
WIthin devtools, disabling the .modal-body max-height: 90% for large screens seems to take care of it. probably related to the height-to-width ratio?

![screenshot from 2018-02-09 10-33-35](https://user-images.githubusercontent.com/5650145/36038292-e316e234-0d84-11e8-9a46-cdd7eef20d83.png)

**Comment by jwhaney** [comment]
I am unable to replicate this issue with a local build or prod.

**Comment by jwhaney** [comment]
I'm closing this for now because I was unable to replicate the issue at all. The problem may be occurring due to certain versions of Chrome or possibly certain OS's (linux distros) may have something to do with it.
