### ISSUE TITLE
Null Statistics Populating

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/lake-gallery#13]
There are two values which contain null statistics that are populating on the Lake Gallery website. 
I have only encountered this issue with Lake Kurth so far. 
The fields that populate the null values are Full Elevation gal: and Dam width: 
I deleted original statistics page, resubmitted with same null values and got the same result. 
![image](https://user-images.githubusercontent.com/23489372/36039559-71dd44f6-0d88-11e8-9f3c-fe2feb435a78.png)

**Comment by jwhaney** [comment]
resolved via commit 64b556680e4e04a0227ca494e762d307c7ec31db
