### ISSUE TITLE
status of overlay layers

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#133]
what is the future of the overlay layers on lakes of texas? what i mean is, are we still planning to keep and do something with these layers in the future? right now, they are not present in the application but I have all the code to include them if we plan to in the future. I'm asking because I am going through the code and cleaning it up. if you aren't sure, that's fine too, i'll just keep the code.

overlay layers:
- boat ramps
- channel markers
- hazards
- parks

**Comment by csidenblad** [comment]
@jwhaney I know that Richard would like to include these types of layers in the application in the future. The issue Lauren and I were having is that we do not have this information for all the lakes. That was the main reason we decided to remove them for the time being.
