### ISSUE TITLE
Google Imagery changes

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#146]
email received on 8/21/20

> Hi John,

>I gave AppGeo the link to our Lakes of Texas app because it was the easiest one I could think of that is serving the Texas Imagery Service. As of today, they switched out the Google composite with one they built instead of the tile api they were using from Google. This is all because our contract with Google ends at the end of this month. No more imagery updates from Google, but we’ll continue to serve out all the imagery we have from them to date.

>__This is a long way to say we’ll need to change the “G” Google symbol on the LOT because eventually this layer will serve Hexagon imagery as opposed to Google imagery. That switch will not happen until later this year or early in 2021 when we have new 2020 Hexagon imagery statewide, so definitely no rush on this minor detail. Maybe the new graphics person could help with a logo for the Texas Imagery Service?__

>Perhaps I’m writing this out now and sending to you and Chelsea both so I’m not the only one to remember we’ll need to change this 😉

>Thanks!
Gayla

**Comment by gmullins** [comment]
@jwhaney I am closing this issue since this app will no longer be maintained as it is, at least not for this smallish enhancement.

**Comment by gmullins** [comment]
@jwhaney Err. I don't think I have rights to close it.
