### ISSUE TITLE
Custom Logo and Lake symbol 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/lake-gallery#25]
these are good starting points, ill come up with some ideas

-chris

From: Chelsea Sidenblad <Chelsea.Sidenblad@twdb.texas.gov>
Date: Tuesday, January 8, 2019 at 11:01 AM
To: Chris Ledesma <Chris.Ledesma@twdb.texas.gov>
Cc: Lauren Kirk <Lauren.Kirk@twdb.texas.gov>
Subject: Custom Logo and Symbol for Lake Gallery

Hey Chris, 
 
I was hoping we could get your help with creating a custom logo and a ‘lake’ symbol to be included in the updated version of the Lake Gallery. 
 
Firstly, we would like to create a custom logo for the Lakes of Texas App (formally known as Lake Gallery, aka Lake Atlas, aka Peter Lakes’ Lakes). We haven’t hammered out anything specific but I was thinking a Texas outline placed behind some blue waves might be simple yet professional looking. I really like the aesthetic of this first example. 
   
 
Secondly, we would also like to have a ‘lake extent’ symbol created to act as a ‘home button’ for the full lake extent. For this we were thinking something more abstract like a meatball with waves. 
  
 
 
These images are just example photos I pulled from google to help piece together the vision, I have them saved here, M:\RDC\Staff\Chelsea\Workflows\RequirementsSnipIts, if you need to access them . Please let me know if you have any questions or if there is anything else I can help do to help the process along. 
Thank you for your help, 
 
Chelsea

**Comment by jwhaney** [comment]
@csidenblad --> is this issue resolved?

**Comment by csidenblad** [comment]
@jwhaney this is completed. Sorry for slacking
