### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/lake-gallery#26]
@christoball please send @csidenblad and I mockups of symbology, logos, and layout by end of the day 3/22/2019.  Please also include samples in dark mode too.  Thank you!! @mitchellryant @LaurenKirk

**Comment by mitchellryant** [comment]
![lakesoftexas_logo_texaslake_oblique](https://user-images.githubusercontent.com/8459928/55188226-da27c980-5168-11e9-8c39-18721192fb0c.jpg)
![lakesoftexas-mockup-march-27-dark-mode](https://user-images.githubusercontent.com/8459928/55188230-dbf18d00-5168-11e9-97c2-3f9673da5510.jpg)
![lakesoftexas-mockup-march-27-light-mode](https://user-images.githubusercontent.com/8459928/55188236-ddbb5080-5168-11e9-8859-57c4bba213de.jpg)
