### ISSUE TITLE
Feedback or Comment link in About page

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#28]
add a way for public to submit form for corrections, additional content/text/info, or any other info related to a lake; connect to contact app.

- allows users to provide suggestions, stories, or questions
- custom form like texas imagery service?

**Comment by jwhaney** [comment]
currently, the public has a way to contact us with comments, suggestions, feedback, etc, with the general contact form.

![image](https://user-images.githubusercontent.com/13525011/59379509-6daa7880-8d1c-11e9-9951-4f34804ce125.png)

I'm not sure we need a custom form just for this application. Will circle back to this later...

**Comment by csidenblad** [comment]
@jwhaney we would like to add option to the existing contact page to include "Lakes of Texas" as the reason for contact. 
Keep language for contact on 'About Us' as is.

**Comment by jwhaney** [comment]
related: contact-app/issues/27

**Comment by jwhaney** [comment]
resolved with commit 265bffa92f31fdfd482f59062ef728594cf07ca4
