### ISSUE TITLE
Replace Regions dropdown with Home "Texas" icon button

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#39]
“Texas” button will function as a home button to return user to statewide extent. Could be placed on right hand side of Navigation Bar, replacing “regions” dropdown, or add new button, with state silhouette, just below (+/-) zoom buttons.

**Comment by jwhaney** [comment]
I created this issue since it was on the requirements doc, and maybe we will end up implementing it down the line, but I do have a fundamental UX issue with this. 

I'm definitely open to discussing it further if you guys like. My point is that a 'Home' button to send the user back to the main landing page of the app is what I would call a global application functionality, not a lake/story specific map functionality. Global app functions should always be in a Nav bar at the top of the page, or in a tool drawer or menu drop down of some sort. Global app functions should exist wherever a user is within the application.

My opinion, if we add a zoom to extent option near the time slider like in Chris' mockup, and we are planning to restrict the user to the the specific lake area so they can't pan around, we just remove the 'Home' or 'Texas' tool/button in the map. If users want to return to the main home page, we can add a home button in the nav or they can just click the app logo in the nav. We could add a tooltip/on hover text to say 'Go back home' or whatever. But, the back to home functionality should exist in the navigation bar since it is a navigation function.

Let me know what yall think.

**Comment by LaurenKirk** [comment]
@jwhaney Agreed.  Lets make the "regions" drop down turn into a "texas" button in the nav bar to take the user to state level.  Add a "lake extent" button to the tool dialogue that takes user back to the full extent of the lake itself.

**Comment by jwhaney** [comment]
Got it. Regions dropdown replaced with Home 'Texas' icon button and a lake extent tool in the tool dialogue for each lake story map.
