### ISSUE TITLE
Remove excess layers from map and from data sources section of About page

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#41]
Remove all additional layers from Layer Table of Contents (boat ramps, hazards, parks, etc…) Only layers that should be available in TOC are the lake polygon layer, ~~dam points layer~~, Texas Imagery Service (not selectable but contains link to Texas Imagery Service page), and available historical layers.

Data: 
i. https://tnris.org/texas-imagery-service/
ii. Base Imagery: Texas Imagery Service source credit should be listed as such.

**Comment by jwhaney** [comment]
does this item in the requirements doc conflict with Chris' mockup? The mockup shows no dam points layer and no link to texas imagery service? If any of you can provide clarity on this, I would appreciate it.

![image](https://user-images.githubusercontent.com/13525011/56586438-5a452180-65a5-11e9-9887-6c05090cde9d.png)

**Comment by LaurenKirk** [comment]
@jwhaney we would like to add the dam point layer to the tool dialogue box at a later date when we have the data.  We anticipate it looking like a check box similar to the "Lake Outline" box.  

We will need to get more information from Gayla, regarding the future of the Texas Imagery Service and its relationship with LOT.  We still want a hyperlink for "current" imagery though.  Hyperlink to the Texas Imagery Service page for the time being.
