### ISSUE TITLE
Tool dialog/time slider expanded on desktop and collapsed on mobile

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#42]
Table of Contents will remain expanded on desktop and collapsed when app is being viewed on mobile or other device.

Layers TOC should be expanded with all layers visible when in story mode.

**Comment by jwhaney** [comment]
A little confused on this one also. Can someone clarify what "Layers TOC" is? if this is referring to the the current layers that are on the lake gallery now, this issue conflicts with Chris' mockup again. I was under the impression we are removing the layers in the map, except for what is showing in the image below which is only the lake outline polygon and a zoom to full extent function.

![image](https://user-images.githubusercontent.com/13525011/56586833-0ab32580-65a6-11e9-853d-381dafc15993.png)

**Comment by LaurenKirk** [comment]
@jwhaney "Layer TOC" is now the tool dialogue where the time slider and additional layers will exist.
