### ISSUE TITLE
Add historical imagery layers to Layer TOC and remove the time slider

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#43]
Function: Time slider will no longer appear in the bottom right of page, historical imagery layers will now be in the Layer TOC. We would like to add data.tnris.org links to the historical collections in the TOC. Only one layer may be selected and visible at a time. If historic layer is selected, imagery swiper appears for use.

**Comment by jwhaney** [comment]
I'm gonna need some clarification on this one as well. This requirement also conflicts with the mockup.

**Comment by jwhaney** [comment]
![image](https://user-images.githubusercontent.com/13525011/56588011-2b7c7a80-65a8-11e9-8619-92dcf30439b1.png)

**Comment by LaurenKirk** [comment]
@jwhaney  Time slider will no longer appear in the bottom right of page, historical imagery layers will now be in the tool dialogue in the future we would like to add hyperlinks to specific collections listed on the time slider.

**Comment by jwhaney** [comment]
@LaurenKirk, just to clarify...

- there will be NO layer TOC
- evntually, the years above the ticks in the time slider will have links to data.tnris.org historical imagery collections

is this correct?

**Comment by LaurenKirk** [comment]
@jwhaney affirmative.  TOC is dead to us.  Replaced by tool dialogue.

**Comment by jwhaney** [comment]
ok then i'm gonna close this issue because we are not getting rid of the time slider/tool dialog
