### ISSUE TITLE
Add YEAR and collection link to historical imagery layers in time slider/tool dialog

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#44]
Users will be able to view historical collections in the Layer TOC as Originator-Year with hyperlinks to collection on data.tnris.org so they can read any metadata about the collection and potential download.

**Comment by jwhaney** [comment]
@LaurenKirk, is this issue still relevant since old TOC is going away?

**Comment by LaurenKirk** [comment]
@jwhaney yes, still relevant.  we would like to add the originator (txtod, usda, etc...) in addition to the year on the time slider inside the tool dialogue.

**Comment by jwhaney** [comment]
@LaurenKirk, do all the originators have acronyms or something short? Even if they are all short originator names, that could get crowded real fast. Some of the lakes have 5 or more historical imagery layers in the time slider. 

If there will eventually be a link to the data.tnris.org collection itself with originator and all other info/metadata, is it necessary to display the originator in the time slider? just seems like it will clutter the tool dialog.

just playing devils advocate here. if you guys want it, it can be done.

**Comment by LaurenKirk** [comment]
@jwhaney we see your point. we dont like it but we agree. fine, have it your way.

**Comment by jwhaney** [comment]
resolved with commit 53b93e36df02b332119de9e452767cba6d6f90c7
