### ISSUE TITLE
Historical layer on, swipe bar appears

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#48]
Only one historical layer can be turned on at a time, if a historical layer is selected then the Imagery Swiper appears at the center of the map.

**Comment by jwhaney** [comment]
@LaurenKirk @csidenblad, is this functionality different than what exists now? please provide clarification.

**Comment by LaurenKirk** [comment]
No, functionality is not different than currently displayed on Lake Gallery.  Just stating how it should function for documentation sake.

**Comment by jwhaney** [comment]
ok so i'm gonna go ahead and close this issue then since the current version already has this functionality.
