### ISSUE TITLE
Change lake story column background color to blue/grey & text color changes

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#52]
Keep these colors for our color scheme. 
i. Primary: #2F4857
ii. Secondary: #D9D9D9
iii. Alternative:  #F29D27
iv. Story Text: #FFFFFF
v. Lake polygon outlines and points: #5692D1

**Comment by jwhaney** [comment]
@LaurenKirk @csidenblad, white text (#FFFFFF) on white background (see mockups) or white text on blue/grey background? this is another one of those conflicts between requirements doc and mockups. need clarification please.

![image](https://user-images.githubusercontent.com/13525011/56831990-3cd7b800-6830-11e9-8cd0-36e7cb0ce82e.png)

**Comment by csidenblad** [comment]
@jwhaney @LaurenKirk @christoball We have addressed this in issue #56. https://github.com/TNRIS/lake-gallery/issues/56
Waiting for chris to get back with hex values based on what was used in the mock up.

**Comment by christoball** [comment]
Light Mode with Hex
![lakesoftexas-mockup-light-mode-withHEX](https://user-images.githubusercontent.com/1877550/56916670-15c2f580-6a7f-11e9-9634-bbafdf9fe167.jpg)

**Comment by christoball** [comment]
Dark Mode with Hex
![lakesoftexas-mockup-dark-mode-withHEX](https://user-images.githubusercontent.com/1877550/56917331-da292b00-6a80-11e9-9575-33f4c6202fd4.jpg)

**Comment by jwhaney** [comment]
just a heads up, dark mode can maybe be added at a later time as an enhancement but right now i'm just gonna go with the light/traditional colors (first mockup image above).

**Comment by LaurenKirk** [comment]
@jwhaney sounds great.  Thank you @christoball for adding the color values!!
