### ISSUE TITLE
Create ledger to track statistics for lakes that do not have WDFT link

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/lake-gallery#53]
This is an internal ledger to track updates for lakes that do not have WDFT links. Can we code a monthly/quarterly notification routine to email us with updates about which lakes need to be reviewed?

**Comment by jwhaney** [comment]
gonna need some clarification on this one i think

**Comment by LaurenKirk** [comment]
@jwhaney The ledger is something the RDC will create and be responsible for towards the end of the project.  We will want to create reminders/notifications for updates periodically as WDFT is updated.
