### ISSUE TITLE
Decade Overlap

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/lake-gallery#6]
Decade years are overlapping on historical slider when too many years are present. 
Lake Athens is an example.
![image](https://user-images.githubusercontent.com/23489372/35937726-c3e5f680-0c0c-11e8-89f7-c9adaa9f5e06.png)

**Comment by jwhaney** [comment]
resolved on develop branch via commit fa0a14cf5a35da963ef5fc588f774fc52e2e1b4d
