### ISSUE TITLE
Modal Instruction Updates

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/lake-gallery#74]
- [x] Remove all references to Regions (i.e. Step 2: Hover over markers to view lake name and region. And from pop-ups)

- [x]  Can we please phrase Step 3 as "Or click a marker to go to Lake Story" Flip steps 3 and 4 to explain lake polygons before pop-ups and story.

- [x] remove Step 5

- [x] In Story Instructions rephrase Step 2 to say "Click a content section header to jump to different sections of the story or scroll through to full story."

- [x] In Story Instructions swap Steps 4 and 5. We want the instruction for the swipe tool to come first. 

- [x] Add Step 6 "To return to Statewide Extent click the Logo" 

@jwhaney

**Comment by csidenblad** [comment]
- [ ] please remove the link to "Jump to Story Instructions". Has been causing mass confusion and delay. Keep all instructions in single catagory

**Comment by jwhaney** [comment]
complete via PR#75
