### ISSUE TITLE
Missing Google Imagery

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/lake-gallery#8]
Google imagery is unable to load all tiles when zoomed to 300m. 
At 200m and 500m scale, imagery loads completely. Refreshing page does not resolve issue.
Lake Kurth is an example. 
![image](https://user-images.githubusercontent.com/23489372/35943719-9b1774aa-0c1f-11e8-9cfb-baa4a82d4b0b.png)

**Comment by adambreznicky** [comment]
my initial reaction is that this is a timing issue for specific load instances and is replicable. not something in the code but with the service and the internet connection at that time of load for the user.

**Comment by jwhaney** [comment]
I agree with Adam. I can't consistently replicate the issue, although I do see what Chelsea is talking about. I am gonna close this out because I don't think this is an issue with the application itself but the service or bandwidth at the time.
